# Site settings é…ç½®ç«™ç‚¹
title: 'Hamburger-burgerham :D'
description: 'HELLO HAMBUGGER'
keywords: 'hamburger_text'
url: 'https://hamburgerdog.github.io' # your host

# nav ä¸­æ–‡å­—ç¬¦ç©ºæ ¼ï¼š&emsp;
nav: # æœ€ä½³ä½“éªŒ å…­ä¸ªæ ‡ç­¾ ä¸”æœ€å¥½æ¯ä¸ªæ ‡ç­¾ä¸è¶…è¿‡4ä¸­æ–‡å­—
 é¦–é¡µ: '/'
 æ ‡ç­¾: '/tags.html'
 æ—¶é—´çº¿: '/timeline.html'
 å…³äºåšä¸»: '/about.html'
 å‹æƒ…é“¾æ¥: '/friendLink.html'

# åšä¸»
author: true
name: 'oneShowWuJiang'
NickName: 'Hambuger'
webtitle: 'xjosiah_page'
bio: 'å·¥ä½œä¸€å¹´ | å¯ä»¥ä¹±å¼€ç©ç¬‘ | å‰ç«¯å°ç éš†~'
about: true
aboutyou: 'åˆ«æ‹¿ä½ çš„ä»£ç å½“è‰ç¨¿~ ğŸ“² <br> æ„¿æˆ‘èˆªå‘å¤§æµ· æ‰¿è½½ä½ çš„ä¿¡èµ–ï½ <br>'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:JosiahHong@qq.com'
  weixin: 'assets/wechat.jpg' # ä½ çš„å¾®ä¿¡äºŒç»´ç å­˜æ”¾çš„åœ°å€
  qq: 'assets/qq.png' # ä½ çš„qqäºŒç»´ç å­˜æ”¾çš„åœ°å€ or http://wpa.qq.com/msgrd?v=3&uin='ä½ çš„QQå·'&site=qq&menu=yes
  github: 'https://github.com/hamburgerdog'
  Codepen: 'https://codepen.io/'
  weibo: '404.html'
#  instagram: 'https://www.instagram.com/'
#  Twitter: 'https://twitter.com/'
#  Dribbble: ''
#  Facebook: ''
#  Google: ''
#  zhihu: ''
#  juejin: ''
#  twitch: ''

# åˆ†é¡µ
paginate: 4
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# ä»£ç é«˜äº® ä½¿ç”¨rouge
highlighter: rouge
# ä»£ç é«˜äº®ä¸»é¢˜ä½¿ç”¨pygmentsä¸»é¢˜: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango ä»»é€‰ä¸€ä¸ªä½ å–œæ¬¢çš„ä¸»é¢˜åç§°å¡«åœ¨ä¸‹é¢çš„å•å¼•å·ä¸­
pygmentsTheme: 'tango'

# å‹æƒ…é“¾æ¥
friends:
  my_little_airplay: 'http://175.24.126.146/#/home'
  æ°¸èªåŒå­¦çš„åšå®¢: 'https://blog.situ2001.com/'
  ç½‘é¡µè®¾è®¡ä½œå“å±•ç¤º: 'http://xjosiah.gitee.io/web_page/'

# è¯„è®º æœ€ä½³ä½“éªŒ åœ¨disqusã€livereå’ŒGitmentä¹‹é—´ä¸‰é€‰ä¸€
# disqus è¯„è®º
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# æ¥å¿…åŠ›è¯„è®º
livere: false
livere_uid: 'MTAyMC81MTk3Ni8yODQ1Nw==' # MTAyMC8zNDI2OS8xMDgwNg== my:MTAyMC81MTk3Ni8yODQ1Nw=='
# Gitmentè¯„è®º OAuth Application
Gitment: false
Gitment_owner: ''  # githubç”¨æˆ·å
Gitment_repo: ''  # githubåšå®¢å­˜æ”¾çš„ä»“åº“å
client_id: ''  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_id
client_secret: ''  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_secret

#leadcloudæ„å»ºçš„valineè¯„è®º
valine: true
valine-appid: 'nyuCPTrEVDOEOSIzIx3vqxsD-9Nh9j0Va'
valine-appkey: '25yxQJLkrDqdbicf3FBXtgqE'
#gravatar.cat.net æä¾›çš„è¯„è®ºå¤´åƒæœåŠ¡
valine-pic: 'retro'


# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# ç™¾åº¦ç»Ÿè®¡ åœ¨baidu-urlé‡Œå¡«å†™è‡ªå·±ç›¸å…³çš„urlä»£ç 
baidu: false
baidu-url: ''
# è°·æ­Œåˆ†æ åœ¨google-IDé‡Œå¡«å†™è‡ªå·±åœ¨è°·æ­Œåˆ†æè·å¾—çš„è¿½è¸ªID
google: false
google-ID: ''

# åšå®¢å¤´ä¿¡æ¯å¤‡é€‰é¢œè‰²ï¼ˆè¯¥éƒ¨åˆ†åœ¨ç«™ç‚¹ä¸­ä¸å……å½“ç«™ç‚¹å˜é‡ï¼Œå°†å…¶å†™åœ¨postçš„å¤´ä¿¡æ¯ä¸­ç”¨æ¥å……å½“é¡µé¢å˜é‡ï¼‰
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
