# Site settings é…ç½®ç«™ç‚¹
title: 'Hamburger-burgerham :D'
description: 'HELLO HAMBUGGER'
keywords: 'hamburger_text'
url: 'https://hamburgerdog.github.io' # your host

# nav ä¸­æ–‡å­—ç¬¦ç©ºæ ¼ï¼š&emsp;
nav: # æœ€ä½³ä½“éªŒ å…­ä¸ªæ ‡ç­¾ ä¸”æœ€å¥½æ¯ä¸ªæ ‡ç­¾ä¸è¶…è¿‡4ä¸­æ–‡å­—
#  é¦–é¡µ: '/'
#  æ ‡ç­¾: '/tags.html'
#  æ—¶é—´çº¿: '/timeline.html'
#  å…³äºåšä¸»: '/about.html'
#  å‹æƒ…é“¾æ¥: '/friendLink.html'

# åšä¸»
author: true
name: 'oneShowWuJiang'
NickName: 'Hambuger'
webtitle: 'aboutMe'
bio: 'å¤§äºŒåœ¨è¯» | ä¹±å¼€ç©ç¬‘â€‹â€‹â€‹ | å­¤å‚²æŒ‘æˆ˜è€…'
about: true
aboutyou: 'å¹³æ—¶å†™ç‚¹ä»£ç çš„åºŸé’ï¼Œæ²¡äº‹å¤šè”ç³» ğŸ“² <br> æ„¿æˆ‘èˆªå‘å¤§æµ· æ‰¿è½½ä½ çš„ä¿¡èµ– '
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:JosiahHong@qq.com'
#  weixin: 'assets/wechat.jpg' # ä½ çš„å¾®ä¿¡äºŒç»´ç å­˜æ”¾çš„åœ°å€
  qq: '/404.html' # ä½ çš„qqäºŒç»´ç å­˜æ”¾çš„åœ°å€ or http://wpa.qq.com/msgrd?v=3&uin='ä½ çš„QQå·'&site=qq&menu=yes
  github: 'https://github.com/hamburgerdog'
  Codepen: 'https://codepen.io/'
  weibo: 'https://www.weibo.com/'
  instagram: 'https://www.instagram.com/'
  Twitter: 'https://twitter.com/'
#  Dribbble: ''
#  Facebook: ''
#  Google: ''
#  zhihu: ''
#  juejin: ''
#  twitch: ''

# åˆ†é¡µ
paginate: 1
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# ä»£ç é«˜äº® ä½¿ç”¨rouge
highlighter: rouge
# ä»£ç é«˜äº®ä¸»é¢˜ä½¿ç”¨pygmentsä¸»é¢˜: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango ä»»é€‰ä¸€ä¸ªä½ å–œæ¬¢çš„ä¸»é¢˜åç§°å¡«åœ¨ä¸‹é¢çš„å•å¼•å·ä¸­
pygmentsTheme: 'default'

# å‹æƒ…é“¾æ¥
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# è¯„è®º æœ€ä½³ä½“éªŒ åœ¨disqusã€livereå’ŒGitmentä¹‹é—´ä¸‰é€‰ä¸€
# disqus è¯„è®º
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# æ¥å¿…åŠ›è¯„è®º
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitmentè¯„è®º OAuth Application
Gitment: false
Gitment_owner: ''  # githubç”¨æˆ·å
Gitment_repo: ''  # githubåšå®¢å­˜æ”¾çš„ä»“åº“å
client_id: ''  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_id
client_secret: ''  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# ç™¾åº¦ç»Ÿè®¡ åœ¨baidu-urlé‡Œå¡«å†™è‡ªå·±ç›¸å…³çš„urlä»£ç 
baidu: false
baidu-url: ''
# è°·æ­Œåˆ†æ åœ¨google-IDé‡Œå¡«å†™è‡ªå·±åœ¨è°·æ­Œåˆ†æè·å¾—çš„è¿½è¸ªID
google: false
google-ID: ''

# åšå®¢å¤´ä¿¡æ¯å¤‡é€‰é¢œè‰²ï¼ˆè¯¥éƒ¨åˆ†åœ¨ç«™ç‚¹ä¸­ä¸å……å½“ç«™ç‚¹å˜é‡ï¼Œå°†å…¶å†™åœ¨postçš„å¤´ä¿¡æ¯ä¸­ç”¨æ¥å……å½“é¡µé¢å˜é‡ï¼‰
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
